export  const JWT_PUBLIC_KEY = process.env.JWT_PUBLIC_KEY ||`-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAswRl1HH8dAhc/D6iR9g/
DvdqklG88FkWYeKZqOPhM8xmohmdJNkG4Kcf2xXOS38SUPlDOcZx5OVb7M3QNmph
UpcJaRgq4VhpGhUCkmLhjgfLfu2Ej+hFT9qBPRuJbXIorBUoGNcVzyBaC37LjoTK
vBslUrP9u0ZEIr3mgwxxtHsIAfjp9eeP4TuHIpiMbNkIu3wXBmjrHXccbgiiQM2P
YyGx9OYXtiXTIIt7dFDarmZzxuuTFeKPvvrl6/cGH/A7T3Ad7NzN+EFpk6weajeX
IhOpFrJnIIdWj9hss5GeQ7j02CzSHC2WV0ZG10Fp76tlmJPAOm7DKiWoHH7Gxsx3
yQIDAQAB
-----END PUBLIC KEY-----
`;